<?php

namespace Coffeeandbrackets\UniqueCodeBundle\Repository;
use Coffeeandbrackets\UniqueCodeBundle\Entity\Campaign;

/**
 * CodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastClearByCampaign(Campaign $campaign){

        $config = $this->getEntityManager()->getConfiguration();
        $config->addCustomNumericFunction('INT', 'Coffeeandbrackets\UniqueCodeBundle\Doctrine\Query\CastAsInteger');

        $qb = $this->createQueryBuilder('c');
        $qb->select('c.clear');
        $qb->where('c.campaign = '.$campaign->getId());
        $qb->orderBy('INT(c.clear)', 'desc');
        $qb->setMaxResults(1);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result ? $result['clear'] : 0;
    }

    public function getLastClearNoCampaign(){

        $config = $this->getEntityManager()->getConfiguration();
        $config->addCustomNumericFunction('INT', 'Coffeeandbrackets\UniqueCodeBundle\Doctrine\Query\CastAsInteger');

        $qb = $this->createQueryBuilder('c');
        $qb->select('c.clear');
        $qb->where('c.campaign IS NULL');
        $qb->orderBy('INT(c.clear)', 'desc');
        $qb->setMaxResults(1);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result ? $result['clear'] : 0;
    }
}
