<?php

namespace Coffeeandbrackets\UniqueCodeBundle\Repository;
use Coffeeandbrackets\UniqueCodeBundle\Entity\Campaign;

/**
 * CodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastClearByCampaign(Campaign $campaign){
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.clear');
        $qb->where('c.campaign = '.$campaign->getId());
        $qb->orderBy('c.clear', 'desc');
        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
