<?php

namespace Coffeeandbrackets\UniqueCodeBundle\Repository;

use Doctrine\Common\Collections\Criteria;

/**
 * ForfaitPlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForfaitPlanningRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlaningById($id)
    {
        $criteria = new Criteria();
        $criteria->where($criteria->expr()->eq('forfaitInternalId', $id));

        // Need to have exact match as we are comparing strings, >< operator will do string comparison
        $date   = new \DateTime();
        $orCriteria = new Criteria();
        for ($i = 1; $i <= 12; $i++) {
            $orCriteria->orWhere(
                $orCriteria->expr()->andX($orCriteria->expr()->eq('year', $date->format('Y')), $orCriteria->expr()->eq('month', $date->format('n')))
            );
            $date->add(new \DateInterval('P1M'));
        }
        $criteria->andWhere($orCriteria->getWhereExpression());

        return $this->matching($criteria);
    }
}
