<?php

namespace Coffeeandbrackets\UniqueCodeBundle\Repository;

/**
 * LogCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
