<?php

namespace Coffeeandbrackets\UniqueCodeBundle\Repository;

use Coffeeandbrackets\UniqueCodeBundle\Entity\EmailLog;
use Coffeeandbrackets\UniqueCodeBundle\Event\Email\HotelConfirmationDueEmailSent;
use Coffeeandbrackets\UniqueCodeBundle\Event\Email\UnseenReservationEmailSent;
use Doctrine\Common\Collections\Criteria;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHotelConfirmationDue()
    {
        $criterea = new Criteria();

        $criterea->where($criterea->expr()->isNull('hotelConfirmationDate'));
        $criterea->andWhere($criterea->expr()->isNull('hotelRefuseDate'));
        $criterea->andWhere($criterea->expr()->lte('addDate', (new \DateTime())->sub(new \DateInterval('PT2H'))));

        $qb = $this->createQueryBuilder('r');
        $qb->addCriteria($criterea)
            ->andWhere($qb->expr()->eq(sprintf('(SELECT COUNT(el.id) FROM %s el WHERE el.reservation = r AND el.event = \'%s\')', EmailLog::class, HotelConfirmationDueEmailSent::NAME), 0));

        return $qb->getQuery()->execute();
    }

    public function findUnseen()
    {
        $criterea = new Criteria();

        $criterea->where($criterea->expr()->isNull('hotelConfirmationDate'));
        $criterea->andWhere($criterea->expr()->isNull('hotelRefuseDate'));
        $criterea->andWhere($criterea->expr()->lte('addDate', (new \DateTime())->sub(new \DateInterval('PT4H'))));

        $qb = $this->createQueryBuilder('r');
        $qb->addCriteria($criterea)
           ->andWhere($qb->expr()->eq(sprintf('(SELECT COUNT(el.id) FROM %s el WHERE el.reservation = r AND el.event = \'%s\')', EmailLog::class, UnseenReservationEmailSent::NAME), 0));

        return $qb->getQuery()->execute();
    }
}
