services:
#    unique_code_admin.example:
#        class: Coffeeandbrackets\UniqueCodeAdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.campaign:
            class: Coffeeandbrackets\UniqueCodeAdminBundle\Admin\Campaign
            arguments: [~, Coffeeandbrackets\UniqueCodeBundle\Entity\Campaign, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Campagnes }
            public: true
    admin.reservation:
            class: Coffeeandbrackets\UniqueCodeAdminBundle\Admin\Reservation
            arguments: [~, Coffeeandbrackets\UniqueCodeBundle\Entity\Reservation, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Réservations, label_translator_strategy: sonata.admin.label.strategy.underscore }
    admin.code:
            class: Coffeeandbrackets\UniqueCodeAdminBundle\Admin\Code
            arguments: [~, Coffeeandbrackets\UniqueCodeBundle\Entity\Code, UniqueCodeAdminBundle:GenerateCodes]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Codes }
    admin.customer:
            class: Coffeeandbrackets\UniqueCodeAdminBundle\Admin\Customer
            arguments: [~, Coffeeandbrackets\UniqueCodeBundle\Entity\Customer, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Clients, label_translator_strategy: sonata.admin.label.strategy.underscore }
    admin.email-log:
                class: Coffeeandbrackets\UniqueCodeAdminBundle\Admin\EmailLog
                arguments: [~, Coffeeandbrackets\UniqueCodeBundle\Entity\EmailLog, UniqueCodeAdminBundle:EmailLog]
                tags:
                    - { name: sonata.admin, manager_type: orm, label: Logs emails }