unique_code_homepage:
    path:     /
    defaults: { _controller: UniqueCodeBundle:Default:index }
unique_code_submit_customer_information:
    path:     /submit_customer_information
    defaults: { _controller: UniqueCodeBundle:Default:submitCustomerInformation }
unique_code_ajax_validate_code:
    path:     /ajax-validate-code
    defaults: { _controller: UniqueCodeBundle:Default:ajaxValidateCode }
unique_code_ajax_search_hotel:
    path:     /ajax-search-hotel
    defaults: { _controller: UniqueCodeBundle:Default:ajaxSearchHotel }
unique_code_submit_reservation:
    path:     /submit_reservation
    defaults: { _controller: UniqueCodeBundle:Default:submitReservation }
unique_code_view_reservation:
    path:     /view_reservation/{id}
    defaults: { _controller: UniqueCodeBundle:Default:viewReservation }
unique_code_accept_reservation:
    path:     /accept_reservation/{id}
    defaults: { _controller: UniqueCodeBundle:Default:acceptReservation }
unique_code_hotel_refuse_reservation:
    path:     /hotel-refuse-reservation/{id}
    defaults: { _controller: UniqueCodeBundle:Default:hotelRefuseReservation }
unique_code_notification:
    path:     /notification
    defaults: { _controller: UniqueCodeBundle:Default:notification }
unique_code_post_hotel_refuse_reservation:
    path:     /post-hotel-refuse-reservation/{id}
    defaults: { _controller: UniqueCodeBundle:Default:postHotelRefuseReservation }
unique_code_customer_reservation_action:
    path:     /customer-reservation-action/{id}
    defaults: { _controller: UniqueCodeBundle:Default:customerReservationAction }
unique_code_ajax_customer_accept_hotel_proposing:
    path:     /ajax-customer-accept-hotel-proposing/{id}
    defaults: { _controller: UniqueCodeBundle:Default:ajaxCustomerAcceptHotelProposing }
unique_code_ajax_customer_decline_hotel_proposing:
    path:     /ajax-customer-decline-hotel-proposing/{id}
    defaults: { _controller: UniqueCodeBundle:Default:ajaxCustomerDeclineHotelProposing }
#Must be last to not hijack any other route
unique_code_campaign:
    path:     /{campaignCode}
    defaults: { _controller: UniqueCodeBundle:Default:index }