unique_code_homepage:
    path:     /
    defaults: { _controller: UniqueCodeBundle:Default:index }
unique_code_submit_customer_information:
    path:     /submit_customer_information
    defaults: { _controller: UniqueCodeBundle:Default:submitCustomerInformation }
unique_code_submit_reservation:
    path:     /submit_reservation
    defaults: { _controller: UniqueCodeBundle:Default:submitReservation }