unique_code_homepage:
    path:     /
    defaults: { _controller: UniqueCodeBundle:Default:index }
unique_code_submit_customer_information:
    path:     /submit_customer_information
    defaults: { _controller: UniqueCodeBundle:Default:submitCustomerInformation }
unique_code_submit_reservation:
    path:     /submit_reservation
    defaults: { _controller: UniqueCodeBundle:Default:submitReservation }
unique_code_view_reservation:
    path:     /view_reservation/{id}
    defaults: { _controller: UniqueCodeBundle:Default:viewReservation }
unique_code_accept_reservation:
    path:     /accept_reservation/{id}
    defaults: { _controller: UniqueCodeBundle:Default:acceptReservation }