services:
    unique_code.check_code:
        class: Coffeeandbrackets\UniqueCodeBundle\Service\CheckCode
        arguments: ["@doctrine.dbal.local_connection"]
    unique_code.mailer:
        class: Coffeeandbrackets\UniqueCodeBundle\Service\Mailer
        arguments:
            - "@mailer"
            - "@templating"
    unique_code.reservation:
            class: Coffeeandbrackets\UniqueCodeBundle\Service\Reservation
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@event_dispatcher"
                - "@unique_code.campaign"
                - "@unique_code.hotels"
    unique_code.code_status_subscriber:
            class: Coffeeandbrackets\UniqueCodeBundle\Event\CodeStatusSubscriber
            arguments:
                - "@workflow.status_code"
                - "@doctrine.orm.entity_manager"
            tags:
                - { name: kernel.event_subscriber }
    unique_code.email_subscriber:
            class: Coffeeandbrackets\UniqueCodeBundle\Event\EmailSubscriber
            arguments:
                - "@unique_code.mailer"
            tags:
                - { name: kernel.event_subscriber }
    unique_code.campaign:
            class: Coffeeandbrackets\UniqueCodeBundle\Service\Campaign
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@request_stack"
    unique_code.hotels:
            class: Coffeeandbrackets\UniqueCodeBundle\Service\Hotels
            arguments:
                - "@doctrine.orm.entity_manager"