services:
    unique_code.check_code:
        class: Coffeeandbrackets\UniqueCodeBundle\Service\CheckCode
        arguments: ["@doctrine.dbal.extern_connection", "@doctrine.dbal.local_connection"]
    unique_code.mailer:
        class: Coffeeandbrackets\UniqueCodeBundle\Service\Mailer
        arguments:
            - "@mailer"
            - "@templating"
