framework:
    workflows:
        status_code:
            marking_store:
                type: single_state
                arguments:
                    - currentStatus
            supports:
                - Coffeeandbrackets\UniqueCodeBundle\Entity\Code
            places:
                - not_actived
                - actived
                - waiting
                - used
            transitions:
                actif:
                    from: not_actived
                    to:   actived
                request:
                    from: actived
                    to:   waiting
                refuse:
                    from: waiting
                    to:   actived
                accept:
                    from: waiting
                    to:   used